var nome = "Beatriz Alves";
var idade = "22";
var idade2 = "10";
var frase = "Japão é o melhor time do mundo";
//alert(nome + " tem " + idade + " anos");
//alert(idade+idade2);
console.log(nome);
console.log(idade * idade2);
console.log(frase.toLowerCase());
//console.log(frase.toUpperCase());
//console.log(frase.replace("Japão", "Brasil"));
//alert(frase.replace("Japão", "Brasil"));